### ISSUE TITLE
What's the source of the info for nutrients.csv?

### ISSUE THREAD

**Issue by egslava** [j2kun/lp-diet#1]
Hello! Amazing blog post! Thanks so much for the info! :) What's the original source of the information you published in nutrients.csv?

**Comment by j2kun** [comment]
It was the Food and Nutrient Database for Dietary Studies (FNDDS) from the USDA: https://fdc.nal.usda.gov/download-datasets.html

I think mine was the 2016 version? Not sure.

**Comment by j2kun** [comment]
Ah, actually, I think it was a legacy version of that database that is stored here: https://data.nal.usda.gov/dataset/usda-national-nutrient-database-standard-reference-legacy-release

USDA National Nutrient Database for Standard Reference. I think it was SR28...

Sorry, it's been a while and I guess the links from the blog post have died.
